version: 2

project_name: deskconn

before:
  hooks:
    - go mod tidy

builds:
  - id: deskconn
    main: ./cmd/deskconn
    binary: deskconn
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: deskconnd
    main: ./cmd/deskconnd
    binary: deskconnd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: deskconn-vpnd
    main: ./cmd/deskconn-vpnd
    binary: deskconn-vpnd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: release-bundle
    ids:
      - deskconn
      - deskconnd
      - deskconn-vpnd
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

snapshot:
  version_template: "{{ if .Version }}{{ .Version }}-snapshot{{ else }}0.0.0-snapshot{{ end }}"
