#!/bin/sh -e

echo '<?xml version="1.0" standalone="no"?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">

<service-group>
  <name replace-wildcards="yes">%h</name>
  <service>
    <type>_deskconn._tcp</type>
    <port>5020</port>
    <txt-record>realm=deskconn</txt-record>
  </service>
</service-group>' > $SNAP_COMMON/deskconn.service
