#!/bin/sh

CACHE_DIR="$SNAP_COMMON"/pycache
PY=$SNAP/usr/bin/python3.8

rm -rf "$CACHE_DIR"
mkdir -p "$CACHE_DIR"
export PYTHONPYCACHEPREFIX=$CACHE_DIR
$PY -m compileall -j $($PY -c "import multiprocessing; print(multiprocessing.cpu_count())") -x .*\.syntaxerror.py$ -q $SNAP/packages $SNAP/usr/lib/python3.8
